[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
optimizer = true
optimizer-runs = 100
solc_version = "0.8.28"
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
